::frague::fragüe
::gueñas::güeñas
::desague::desagüe
::enjague::enjagüe
::deguella::degüella
::deguelle::degüelle
::deguello::degüello
::deguellan::degüellan
::deguellas::degüellas
::deguellen::degüellen
::deguelles::degüelles
::verguenza::vergüenza
::desverguenza::desvergüenza
::desverguenzas::desvergüenzas
::contiguidad::contigüidad
::sinverguencería::sinvergüencería
::metalinguística::metalingüística
::metalinguístico::metalingüístico
::plurilinguismos::plurilingüismos
::pinguino::pingüino
::pinguinos::pingüinos
::linguística::lingüística
::linguístico::lingüístico
::ambiguedad::ambigüedad
::antiguedad::antigüedad
::cigueña::cigüeña
::bilingue::bilingüe
::guero::güero
::yegueria::yegüería
::yeguería::yegüería
::yegüeria::yegüería
::yeguerias::yegüerías
::yeguerías::yegüerías
::yegüerias::yegüerías
::averiguar::averigüar
::averiguarlo::averigüarlo
::averguenzo::avergüenzo
::averguenza::avergüenza
::averguenzado::avergüenzado
::averguenzados::avergüenzados
;============================
::judio::judío
::judios::judíos
::judia::judía
::judias::judías
::pajaro::pájaro
::acentuan::acentúan
::demas::demás
::defensoria::defensoría
::alla::allá
::extasis::éxtasis
::via::vía
::leyo::leyó
::mejoria::mejoría
::mejorias::mejorías
::empeoraria::empeoraría
::empeorarias::empeorarías
::mejoraria::mejoraría
::mejorarias::mejorarías
::pais::país
::aceptariamos::aceptaríamos
::concurrira::concurrirá
::defendio::defendió
::clasificacion::clasificación
::desclasificacion::desclasificación
::detencion::detención
::atencion::atención
::identificacion::identificación
::muchisimo::muchísimo
::muchisimos::muchísimos
::muchisima::muchísima
::muchisimas::muchísimas
::terminologia::terminología
::venia::venía
::venias::venías
::venian::venían
::civico::cívico
::civicos::cívicos
::civica::cívica
::civicas::cívicas
::paises::países
::terapeútica::terapeútica
::terapeúticas::terapeúticas
::terapeútico::terapeútico
::terapeúticos::terapeúticos
::moderacion::moderación
::prescripcion::prescripción
::gestion::gestión
::administracion::administración
::devaluacion::devaluación
::mineria::minería
::orientacion::orientación
::eliminacion::eliminación
::aceptacion::aceptación
::economia::economía
::indice::índice
::aqui::aquí
::confiteria::confitería
::chocolateria::chocolatería
::union::unión
::sinonimo::sinónimo
::sinonimos::sinónimos
::antonimo::antónimo
::antonimos::antónimos
::leido::leído
::leidos::leídos
::leida::leída
::leidas::leídas
::corionioca::coriónica 
::ahi::ahí
::aun::aún
::comunicacion::comunicación
::calculos::cálculos
::calculo::cálculo
::deberia::debería
::deberias::deberías
::deberian::deberían
::electronico::electrónico
::ingenieria::ingeniería
::decidio::decidió
::ingenierias::ingenierías
::contenia::contenía
::contenian::contenían
::contenias::contenías
::murio::murió
::debia::debía
::debias::debías
::debian::debían
::eleccion::elección
::rebeldia::rebeldía
::rebeldias::rebeldías
::rapidamente::rápidamente
::siguio::siguió
::seguia::seguía
::seguias::seguías
::seguian::seguían
::simbolo::símbolo
::simbolos::símbolos
::innovacion::innovación
::instantanea::instantánea
::metodo::método
::metodos::métodos
::minimo::mínimo
::minimos::mínimos
::navegacion::navegación
::permitia::permitía
::permitias::permitías
::permitian::permitían
::podia::podía
::podias::podías
::podian::podían
::tecnologias::tecnologías
::psicotico::psicótico
::movil::móvil
::moviles::móviles
::aseguro::aseguró
::codigo::código
::codigos::códigos
::circulo::círculo
::circulos::círculos
::conseguis::conseguís
::reunen::reúnen
::nadabamos::nadábamos
::lavabamos::lavábamos
::imagenes::imágenes
::depresion::depresión
::represion::represión
::agresion::agresión
::desvio::devío
::desvion::devíon
::desvian::devían
::caracteristica::característica
::caracteristicas::características
::caracteristico::característico
::caracteristicos::característicos
::panhispánico::panhispánico
::hispánico::hispánico
::desvia::desvía
::desvian::desvían
::segun::según
::podria::podría
::podrias::podrías
::podrian::podrían
::situacion::situación
::asi::así
::opcion::opción
::cotizacion::contización
::sanacion::sanación
::convendria::convendría
::convendra::convendrá
::sera::será
::extincion::extinción
::extension::extensión
::encantaria::encantaría
::lio::lío
::lio::líos
::papi::papí
::papis::papís
::hetero::hétero
::heteros::héteros
::hetera::hétera
::heteras::héteras
::segui::seguí
::pidio::pidió
::revolvia::revolvía
::revolvias::revolvías
::revolvian::revolvían
::afiambro::afiambró
::civilizacion::civilización
::subi::subí
::reunio::reunió
::reunion::reunión
::sucedio::sucedió
::decirselo::decírselo
::decirselos::decírselos
::deduccion::deducción
::direccion::dirección
::redaccion::redacción
::reaccion::reacción
::conduccion::conducción
::respondio::respondió
::utopia::utopía
::agresion::agresión
::vendia::vendía
::vendian::vendían
::periodistico::periodístico
::parasito::parásito
::parasitos::parásitos
::locucion::locución
::conexion::conexión
::programacion::programación
::configuracion::configuración
::analisis::análisis
::caido::caído
::caidos::caídos
::caida::caída
::caidas::caídas
::daltonico::daltónico
::daltonicos::daltónicos
::daltonica::daltónica
::daltonicas::daltónicas
::maquina::máquina
::maquinas::máquinas
::sorprenderia::sorprendería
::investigacion::investigación
::organizacion::organización
::dialogo::diálogo
::numeros::números
::numerologia::numerología
::electroencefalografico::electroencefalográfico
::electroencefalograficos::electroencefalográficos
::electroencefalografica::electroencefalográfica
::electroencefalograficas::electroencefalográficas
::etcetera::etcétera
::pusilanime::pusilánime
::catodico::catódico
::catodicos::catódicos
::catodica::catódica
::decapodo::decápodo
::algido::álgido
::aureo::áureo
::anibal::aníbal
::brotola::brótola
::isoceles::isóceles
::gluteo::glúteo
::gluteos::glúteos
::muerdago::muérdago
::nausea::náusea
::oleo::óleo
::oseo::óseo
::lugubre::lúgubre
::lugubres::lúgubre
::biologias::biologías
::ciencilogia::cienciología
::ciencilogias::cienciologías
::contaminacion::contaminación
::tipologia::tipología
::delfin::delfín
::tipologias::tipologías
::tipologo::tipólogo
::tipologos::tipólogos
::tipologa::tipóloga
::tipologas::tipólogas
::parasintetica::parasintética
::parasinteticas::parasintéticas
::prosodico::prosódico
::prosodicos::prosódicos
::tentaculos::tentáculos
::acronimo::acrónimo
::acronimos::acrónimos
::ambito::ámbito
::analitico::analítico
::analiticos::analíticos
::arabe::árabe
::antilope::antílope
::baculo::báculo
::balsamo::bálsamo
::llegaramos::llegáramos
::britanico::británico
::biologico::biológico
::biologicos::biológicos
::bipedo::bípedo
::hace mas::hace más
::bitacora::bitácora
::bitacoras::bitácoras
::boligrafo::bolígrafo
::bulimico::bulímico
::bulimicos::bulímicos
::bulimica::bulímica
::bulimicas::bulímicas
::cabula::cábula
::candido::cándido
::cantaro::cántaro
::cantico::cántico
::cañamo::cáñamo
::veia::veía
::bronceandome::bronceándome
::reia::reía
::carambanos::carámbanos
::catedratico::catedrático
::catedraticos::catedráticos
::catedratica::catedrática
::catedraticas::catedráticas
::cuspide::cúspide
::cuspides::cúspides
::cronico::crónico
::cronicos::crónicos
::cronica::crónica
::cronicas::crónicas
::cuantica::cuántica
::hectometro::hectómetro
::idoneo::idóneo
::idoneos::idóneos
::idonea::idónea
::idoneas::idóneas
::kilometro::kilómetro
::kilometros::kilómetros
::linguistica::lingüística
::linguística::lingüística
::linguisticas::lingüisticas
::linguísticas::lingüísticas
::linguistico::lingüístico
::linguístico::lingüístico
::linguisticos::lingüisticos
::linguísticos::lingüísticos
::intimo::íntimo
::intimos::íntimos
::intrinsico::intrínsico
::ironico::irónico
::magnificio::magnífico
::lapida::lápida
::utero::útero
::salis::salís
::vastago::vástago
::vastagos::vástagos
::vastaga::vástaga
::vastagas::vástagas
::yambico::yámbico
::zingaro::zíngaro
::zodiaco::zodíaco
::zodiacos::zodíacos
::zodiaca::zodíaca
::zodiacas::zodíacas
::zurumbatico::zurumbático
::zurumbaticos::zurumbáticos
::pontifice::pontífece
::putrido::pútrido
::portico::pórtico
::potasico::potásico
::pirrico::pírrico
::placido::plácido
::prestamo::préstamo
::xilofono::xilófono
::xilofonos::xilófonos
::pildora::píldora
::octageno::octágono
::sulfurico::sulfúrico
::sulfuricos::sulfúricos
::sulfurica::sulfúrica
::sulfuricas::sulfúricas
::subdito::súbdito
::subditos::súbditos
::subdita::súbdita
::subditas::súbditas
::timido::tímido
::timidos::tímidos
::timida::tímida
::timidas::tímidas
::triada::tríada
::triadas::tríadas
::septimo::séptimo
::sordido::sórdido
::sordidos::sórdidos
::sordida::sórdida
::sordidas::sórdidas
::trigesima::trigésima
::trigesimas::trigésimas
::trigesimo::trigésimo
::trigesimos::trigésimos
::sabanas::sábanas
::parametro::parámetro
::parametros::parámetros
::musculo::músculo
::musculos::músculos
::prostibulo::prostíbulo
::prostibulos::prostíbulos
::neoclasico::neoclásico
::neoclasicos::neoclásicos
::neoclasica::neoclásica
::neoclasicas::neoclásicas
::purpura::púrpura
::rabano::rábano
::ñacaro::ñácaro
::parasintentica::parasinténtica
::pildoras::píldoras
::catodicos::catódicas
::dialogos::diálogos
::sucedio::sucedió
::policia::policía
::politica::política
::politicas::políticas
::politico::político
::politicos::políticos
::putaso::putazo
::sabias::sabías
::sabian::sabían
::pelotudaso::pelotudazo
::boludaso::boludazo
::pelotudes::pelotudez
::pelotudés::pelotudez
::boludés::boludez
::boludes::boludez
::perdio::perdió
::sabado::sábado
::musica::música
::unico::único
::unicos::únicos
::unica::única
::unicas::únicas
::motivacion::motivación
::ningun::ningún
::magico::mágico
::tambien::también
::republica::república
::republicas::repúblicas
::publicacion::publicación
::victima::víctima
::victimas::víctimas
::empezo::empezó
::tipografia::tipografía
::tipografias::tipografías
::tipografica::tipográfica
::tipografico::tipográfico
::tipograficas::tipográficas
::tipograficos::tipográficos
::apurese::apúrese
::apurense::apúrense
::latin::latín
::lagrima::lágrima
::lagrimas::lágrimas
::rapido::rápido
::rapidos::rápidos
::rapida::rápida
::rapidas::rápidas
::enciclopedico::enciclopédico
::humoristico::humorístico
::humoristicos::humorísticos
::parentesis::paréntesis
::comico::cómico
::dermatologo::dermatólogo
::dermatologos::dermatólogos
::piramide::pirámide
::plastico::plástico
::geografico::geográfico
::geologico::geológico
::paleontologico::paleontológico
::cupula::cúpula
::hipodromo::hipódromo
::metalurgico::metalúrgico
::histerico::histérico
::penultimo::penúltimo
::cascara::cáscara
::clasico::clásico
::celula::célula
::conyugue::cónyugue
::centripeto::centrípeto
::cubico::cúbico
::economico::económico
::economicos::económicos
::monotono::monótono
::oraculo::oráculo
::sarcastico::sarcástico
::tentaculo::tentáculo
::satelite::satélite
::semantico::semántico
::carceles::cárceles
::acerrimo::acérrimo
::gargola::gárgola
::gargolas::gárgolas
::islamico::islámico
::islamicos::islámicos
::islamica::islámica
::islamicas::islámicas}
::jurasico::jurásico
::jurasicos::jurásicos
::heterogeneo::heterogéneo
::higado::hígado
::higados::hígados
::calido::cálido
::calidos::cálidos
::calida::cálida
::calidas::cálidas
::insipido::insípido
::valia::valía
::valian::valían
::egocentrico::egocéntrico
::egocentricos::egocéntricos
::egocentrica::egocéntrica
::egocentricas::egocéntricas
::engreido::engreído
::engreidos::engreídos
::engreida::engreída
::engreidas::engreídas
::tecnico::técnico
::exageracion::exageración
::tecnicos::técnicos
::fosforo::fósforo
::glandula::glándula
::microfono::micrófono
::microfonos::micrófonos
::abaco::ábaco
::abacos::ábacos
::gotico::gótico
::goticos::góticos
::energico::enérgico
::energicos::enérgicos
::energica::enérgica
::energicas::enérgicas
::dentrifico::dentrífico
::dentrificos::dentríficos
::gotica::gótica
::goticas::góticas
::colera::cólera
::fria::fría
::frias::frías
::ilegitimo::ilegítimo
::rectangulo::rectángulo
::rectangulos::rectángulos
::aritmetica::aritmética
::aritmeticas::aritméticas
::aritmetico::aritmético
::aritmeticos::aritméticos
::telefonica::telefónica
::telefonicas::telefónicas
::ceramica::cerámica
::ceramicas::cerámicas
::ceramico::cerámico
::ceramicos::cerámicos
::antigona::antígona
::didactico::didáctico
::didacticos::didácticos
::didactica::didáctica
::didacticas::didácticas
::agricola::agrícola
::darsela::dársela
::darselas::dárselas
::darselo::dárselo
::darselos::dárselos
::tipico::típico
::tipicos::típicos
::tipica::típica
::dramatico::dramático
::dramaticos::dramáticos
::dramatica::dramática
::dramaticas::dramáticas
::tipicas::típicas
::vibora::víbora
::aca::acá
::energia::energía
::recomendo::recomendó
::bibliografia::bibliografía
::vertice::vértice
::vertices::vértices
::cinematografico::cinematográfico
::problematica::problemática
::problematicas::problemáticas
::problematico::problemático
::problematicos::problemáticos
::xenofobo::xenófobo
::xenofobos::xenófobos
::xenofoba::xenófoba
::xenofobas::xenófobas
::unisono::unísono
::sabados::sábados
::vandalo::vándalo
::zangano::zángano
::repercusion::repercusión
::vandalos::vándalos
::zanganos::zánganos
::palido::pálido
::palidos::pálidos
::palida::pálida
::palidas::pálidas
::tenes::tenés
::película::película
::películas::películas
::hispanico::hispánico
::catastrofe::catástrofe
::realizaran::realizarán
::limite::límite
::limites::límites
::grafia::grafía
::grafias::grafías
::ordenes::órdenes
::de mas::de más
::ser mas::ser más
::que mas::que más
::lo mas::lo más
::de mas::de más
::la mas::la más
::es mas::es más
::pero mas::pero más
::oido::oído
::comoda::cómoda
::comodas::cómodas
::comodo::cómodo
::comodos::cómodos
::graficos::gráficos
::comezon::comezón
::todavia::todavía
::aprobacion::aprobación
::acordeon::acordeón
::votacion::votación
::volare::volaré
::encontre::econtré
::perdon::perdón
::razon::razón
::sabran::sabrán
::tenia::tenía
::tenian::tenían
::tenias::tenías
::bajon::bajón
::velaria::velaría
::dieresis::diéresis
::ortografia::ortografía
::quirurgica::quirúrgica
::quirurgicos::quirúrgicos
::monosilabo::monosílabo
::decia::decía
::parecio::pareció
::simpatico::simpático
::simpaticos::simpáticos
::simpatica::simpática
::simpaticas::simpáticas
::categoria::categoría
::categorias::categorías
::biografia::biografía
::biografias::biografías
::silaba::sílaba
::silabas::sílabas
::autonomia::autonomía
::autonomias::autonomías
::atomica::atómica
::atomicas::atómicas
::contabamos::contábamos
::deciamos::decíamos
::hablabamos::hablábamos
::tentacion::tentación
::tentaria::tentaría
::tentarias::tentarías
::hipocresia::hipocresía
::hipocresias::hipocresías
::hipocrita::hipócrita
::hipocritas::hipócritas
::filosofia::filosofía
::filosofo::filósofo
::filosofa::filósofa
::filosofos::filósofos
::filosofas::filósofas
::sociologia::sociología
::psicologia::psicología
::sociologo::sociólogo
::psicologo::psicólogo
::sociologos::sociólogos
::psicologos::psicólogos
::sociologa::socióloga
::psicologa::psicóloga
::sociologas::sociólogas
::psicologas::psicólogas
::entendi::entendí
::traduccion::traducción
::habia::había
::habian::habían
::habias::habías
::corazon::corazón
::idolo::ídolo
::apostoles::apóstoles
::super::súper
::habran::habrán
::habra::habrá
::dia::día
::dias::días
::gustaria::gustaría
::escandalo::escándalo
::escandalos::escándalos
::facilmente::fácilmente
::utilizacion::utilización
::queria::quería
::querria::querría
::estara::estará
::estaría::estaría
::tontamente::tóntamente
::espectaculo::espectáculo
::espectaculos::espectáculos
::dequeismo::dequeísmo
::laismo::laísmo
::leismo::leísmo
::loismo::loísmo
::arbol::árbol
::arboles::árboles
::bateria::batería
::baterias::baterías
::insistio::insistió
::jamas::jamás
::leon::león
::ordenele::ordénele
::pacifico::pacífico
::pacificos::pacíficos
::pacificv::pacífica
::pacificas::pacíficas
::parecera::parecerá
::parecere::pareceré
::prosegui::proseguí
::poniendome::poniéndome
::quizas::quizás
::senti::sentí
::respondi::respondí
::recorde::recordé
::recordo::recordo
::sentia::sentía
::sentias::sentías
::sentian::sentían
::seras::serás
::subitamente::súbitamente
::tendras::tendrás
::atraganteria::atragantaría
::cancion::canción
::lesion::lesión
::leccion::lección
::trasmision::trasmisión
::sanguinea::sanguínea
::sanguineas::sanguíneas
::falto::faltó
::sanguineo::sanguíneo
::sanguineos::sanguíneos
::tuberculo::tubérculo
::tuberculo::tubérculos
::masoneria::masonería
::nitrogeno::nitrógeno
::juga::jugá
::veintidos::veintidós
::liquido::líquido
::espontaneamente::espontáneamente
::espontaneo::espontáneo
::definicion::definición
::traves::través
::volveria::volvería
::transcurria::transcurría
::tranvia::tranvía
::travesía::travesía
::travesías::travesías
::gramatica::gramática
::gramaticas::gramáticas
::quimica::química
::quimicas::químicas
::quimico::químico
::quimicos::químicos
::ingles::inglés
::aspero::áspero
::titulo::título
::titulos::títulos
::aprobo::aprobó
::biotecnologico::bioteconológico::
::tecnologia::tecnología
::tecnologica::tecnológica
::tecnologicas::tecnológicas
::tecnologico::tecnológico
::tecnologicos::tecnológicos
::masomenos::más o menos
::hungaro::húngaro
::region::región
::renglon::renglón
::testiculo::testículo
::testiculos::testículos
::inflacion::inflación
::mintio::mintió
::alli::allí
::automatico::automático
::automaticos::automáticos
::automatica::automática
::automaticas::automáticas
::caserio::caserío
::caserios::caseríos
::coalicion::coalición
::comenzo::comenzó
::convirtio::convirtió
::debera::deberá
::decian::decían
::discusion::discusión
::discutia::discutía
::discutias::discutías
::discutian::discutían
::electronica::electrónica
::electronicas::electrónicas
::emitiran::emitirán
::encontro::encontró
::expres::exprés
::imbecil::imbécil
::imbeciles::imbéciles
::intencion::intención
::nostalgica::nostálgica
::guia::guía
::guias::guías
::guian::guían
::límite::límite
::límite::límites
::formulas::fórmulas
::interes::interés
::accion::acción
::inaccion::inacción
::ecuacion::ecuación
::adecuacion::adecuación
::informacion::información
::area::área
::comun::común
::sancion::sanción
::oposicion::oposición
::paraiso::paraíso
::peleandose::peleándose
::reunira::reunirá
::tendra::tendrá
::transaccion::transacción
::votarian::votarían
::compulsion::compulsión
::propulsion::propulsión
::combustion::combustión
::ejeccion::ejección
::cutanea::cutánea
::cutaneas::cutáneas
::genetica::genética
::geneticas::genéticas
::helicoptero::helicóptero
::areas::áreas
::seria::sería
::metereologico::metereológico
::ocasion::ocasión
::mio::mío
::mia::mía
::mios::míos
::mias::mías
::logica::lógica
::logico::lógico
::logicas::lógicas
::logicos::lógicos
::dolar::dólar
::dolares::dólares
::revolucion::revolución
::historico::histórico
::historica::histórica
::historicos::históricos
::historicas::históricas
::promocion::promoción
::fraccion::fracción
::division::división
::miercoles::miércoles
::fanatico::fanático
::fanaticos::fanáticos
::fanatica::fanática
::fanaticas::fanáticas
::pendulo::péndulo
::linea::línea
::molecula::molécula
::moleculas::moléculas
::lineas::líneas
::tv::TV
::dnu::DNU
::cuil::CUIL
::tramite::trámite
::tramites::trámites
::telefonia::telefonía
::eligio::eligió
::complico::complicó
::complice::cómplice
::complice::cómplices
::facil::fácil
::faciles::fáciles
::pagina::página
::paginas::páginas
::tecnica::técnica
::tecnicas::técnicas
::busqueda::búsqueda
::busquedas::búsquedas
::canción::canción
::botanica::botánica
::irrigacion::irrigación
::congelación::congelación
::barbaro::bárbaro
::algun::algún
::malisimo::malísimo
::buenisimo::buenísimo
::malisimos::malísimos
::buenisimos::buenísimos
::mismisimo::mismísimo
::sintoma::síntoma
::sintomas::síntomas
::especimen::espécimen
::jovenes::jóvenes
::insolito::insólito
::insolitos::insólitos
::lei::leí
::estupida::estúpida
::estupidas::estúpidas
::estupido::estúpido
::estupidos::estúpidos
::dislexica::disléxica
::dislexicas::disléxicas
::dislexico::disléxico
::dislexicos::disléxicos
::lexica::léxica
::lexicas::léxicas
::lexico::léxico
::lexicos::léxicos
::prorroga::prórroga
::pelicula::película
::peliculas::películas
::proteccion::protección
::cientifico::científico
::cientificos::científicos
::cientifica::científica
::cientificas::científicas
::futbolistico::futbolístico
::especulacion::especulación
::maritimo::marítimo
::maritimos::marítimos
::maritima::marítima
::maritimas::marítimas
::fantasia::fantasía
::fantasticas::fantásticas
::fantastica::fantástica
::fantastico::fantástico
::fantasticos::fantásticos
::descubrio::descubrió
::aleman::alemán
::publicos::públicos
::pesimo::pésimo
::pesimos::pésimos
::volco::volcó
::advirtio::advirtió
::mitico::mítico
::miticos::míticos
::centrico::céntrico
::centricos::céntricos
::centrica::céntrica
::centricas::céntricas
::aparicion::aparición
::teorica::teórica
::teoricas::teóricas
::septimos::séptimos
::septimas::séptimas
::decimo::décimo
::decimos::décimos
::decima::décima
::decimas::décimas
::mitica::mítica
::miticas::míticas
::sesion::sesión
::patetico::patético
::pateticos::patéticos
::patetica::patética
::metia::metía
::metias::metías
::pateticas::patéticas
::ultimo::último
::ultimos::últimos
::ultima::última
::ultimas::últimas
::podra::podrá
::podran::podrán
::articulo::artículo
::articulos::artículos
::mayoria::mayoría
::mayorias::mayorías
::minoria::minoría
::minorias::minorías
::polemica::polémica
::polemicas::polémicas
::polemico::polémico
::polemicos::polémicos
::perdi::perdí
::frigorifico::frigorífico
::frigorificos::frigoríficos
::frigorifica::frigorífica
::frigorificas::frigoríficas
::ademas::además
::edicion::edición
::sobreedicion::sobreedición
::mayuscula::mayúscula
::mayusculas::mayúsculas
::minuscula::minúscula
::minusculas::minúsculas
::cajon::cajón
::boton::botón
::etimologia::etimología
::etimologico::etimológico
::etimologicos::etimológicos
::etimologica::etimológica
::etimologicas::etimológicas
::despues::después
::camion::camión
::natacion::natación
::relación::relación
::estándar::estándar
::estándares::estándares
::basico::básico
::alegria::alegría
::fisica::física
::fisicas::físicas
::fisico::físico
::fisicos::físicos
::conclusion::conclusión
::introduccion::introducción
::minima::mínima
::minimas::mínimas
::maxima::máxima
::maximas::máximas
::astrofisica::astrofísica
::astrofisicas::astrofísicas
::astrofisico::astrofísico
::astrofisicos::astrofísicos
::teoria::teoría
::teorico::teóríco
::práctico::práctico
::prácticos::prácticos
::proposito::propósito
::propositos::propósitos
::podes::podés
::criptografia::criptografía
::práctica::práctica
::prácticas::prácticas
::atletico::atlético
::atleticos::atléticos
::atletica::atlética
::atleticas::atléticas
::limon::limón
::libreria::librería
::librerias::librerías
::criptico::críptico
::cripticos::crípticos
::criptica::críptica
::cripticas::crípticas
::revez::revés
::reves::revés
::transicion::transición
::transision::transición
::transisión::transición
::parrafo::párrafo
::parrafos::párrafos
::camión::camión
::tendria::tendría
::hidrogeno::hidrógeno
::petroleo::petróleo
::molecula::molécula
::moleculas::moléculas
::provocacion::provocación
::peroxido::peróxido
::oxido::óxido
::tendrias::tendrías
::tendrian::tendrían
::cardiaco::cardíaco
::cardiacos::cardíacos
::hibrido::híbrido
::hibridos::híbridos
::hibrida::híbrida
::hibridas::híbridas
::aflojaria::aflojaría
::floreria::florería
::estan::están
::oracion::oración
::tacito::tácito
::mediterraneo::mediterráneo
::artico::ártico
::maximo::máximo
::maximos::máximos
::maxima::maxima
::maximas::maximas
::incomodos::incómodos
::incomodas::incómodas
::lamentosisimo::lamentosísimo
::lamentosisimos::lamentosísimos
::lamentosisima::lamentosísima
::lamentosisimas::lamentosísimas
::respondio::respondió
::version::versión
::campeon::campeón
::personalizacion::personalización
::opinion::opinión
::azucar::azúcar
::azucares::azúcares
::regimen::régimen
::regimenes::regímenes
::cabalistica::cabalística
::cabalistico::cabalístico
::unicamente::únicamente
::seguis::seguís
::inscripcion::inscripción
::formula::fórmula
::guardarselo::guardárselo
::conservarselo::conservárselo
::comision::comisión
::creyendose::creyéndose
::estupidamente::estúpidamente
::desafio::desafío
::desafios::desafíos
::incorrectamente::incorréctamente
::correctamente::corréctamente
::arepentis::arrepentís
::seguira::seguirá
::reproduccion::reproducción
::carton::cartón
::aristocrata::aristócrata
::chupon::chupón
::demografia::demografía
::rectilineo::rectilíneo
::sabiduria::sabiduría
::jugueton::juguetón
::homografo::homógrafo
::sazon::sazón
::conjugacion::conjugación
::obstruccion::obstrucción
::seudonimo::seudónimo
::acordeon::acordeon
::adiccion::adicción
::admiracion::admiración
::cafe::café
::bebera::beberá
::calzon::calzón
::camaron::camarón
::caminara::caminará
::comprension::comprensión
::confirmacion::confirmación
::exclamacion::exclamación
::explicacion::explicación
::justificacion::justificación
::expresion::expresión
::guion::guión
::ilustracion::ilustración
::japones::japonés
::mani::maní
::maricon::maricón
::medicacion::medicación
::poblacion::población
::porton::portón
::carcel::cárcel
::bursatil::bursátil
::chofer::chófer
::futbol::fútbol
::dificil::difícil
::fosil::fósil
::inverosimil::inverosímil
::lider::líder
::marmol::mármol
::retractil::retráctil
::sueter::suéter
::volatil::volátil
::raiz::raíz
::conoci::conocí
::rebelion::rebelión
::recibio::recibió
::rotacion::rotación
::salmon::salmón
::sastifaccion::sastifacción
::sofa::sofá
::solucion::solución
::sustraccion::sustracción
::tiburon::tiburón
::television::televisión
::terminacion::terminación
::determinacion::determinación
::religion::religión
::cabelleria::caballería
::matematica::matemática
::matematicas::matemáticas
::util::útil
::etica::ética
::eticas::éticas
::conjuncion::conjunción
::obsesion::obsesión
::me entro::me entró
::dolia::dolía
::vision::visión
::aguila::águila
::zoologia::zoología
::perfeccion::perfección
::anonimo::anónimo
::anonimos::anónimos
::pasandola::pasándola
::pasandole::pasándole
::pasandoles::pasándoles
::anonima::anónima
::anonimas::anónimas
::estadistica::estadística
::estadisticas::estadísticas
::estadistico::estadístico
::estadisticos::estadísticos
::periodo::período
::sotano::sótano
::carbon::carbón
::querras::querrás
::queria::quería
::pasaria::pasaría
::suspenderia::suspendería
::almorzaria::almorzaría
::comeria::comería
::comia::comía
::veni::vfení
::mostro::mostró
::solucionaria::solucionaría
::el es::él es
::el esta::él está
::el está::él está
::el.::él.
::el"::él"
::el,::él,
::el;::él;
::existia::existía
::existias::existías
::existian::existían
::escribiendote::escribiéndote
;============================
::¿como::¿Cómo
::¿por que::¿Por qué
::por que::por qué
::¿Y como::¿Y cómo
::¿que::¿Qué
::¿cual::¿Cuál
::¿cuales::¿Cuáles
::¿donde::¿Dónde
::¿quien::¿Quién
::¿quienes::¿Quiénes
::¿cuando::¿Cúando
::¿cuanto::¿Cuánto
::¿cuantos::¿Cuántos
::¿cuanta::¿Cuánta
::¿cuantas::¿Cuántas
::¿De que::¿De qué
::¿De cual::¿De cuál
::¿De cuales::¿De cuáles
::¿De donde::¿De dónde
::¿De quien::¿De quién
::¿De quienes::¿De quiénes
::¿De cuando::¿De cúando
::¿De cuanto::¿De cuánto
::¿De cuanta::¿De cuánta
::¿De cuantos::¿De cuántos
::¿De cuantas::¿De cuántas
::¿Y que::¿Y qué
::¿Y cual::¿Y cuál
::¿Y cuales::¿Y cuáles
::¿Y donde::¿Y dónde
::¿Y quien::¿Y quién
::¿Y quienes::¿Y quiénes
::¿Y cuando::¿Y cúando
::¿Y cuanto::¿Y cuánto
::¿Y cuanta::¿Y cuánta
::¿Y cuantos::¿Y cuántos
::¿Y cuantas::¿Y cuántas
::¿Y de que::¿Y de qué
::¿Y de cual::¿Y de cuál
::¿Y de cuales::¿Y de cuáles
::¿Y de donde::¿Y de dónde
::¿Y de quien::¿Y de quién
::¿Y de quienes::¿Y de quiénes
::¿Y de cuando::¿Y de cúando
::¿Y de cuanto::¿Y de cuánto
::¿Y de cuanta::¿Y de cuánta
::¿Y de cuantos::¿Y de cuántos
::¿Y de cuantas::¿Y de cuántas
::¿Y a que::¿Y a qué
::¿Y a cual::¿Y a cuál
::¿Y a cuales::¿Y a cuáles
::¿Y a donde::¿Y a dónde
::¿Y a quien::¿Y a quién
::¿Y a quienes::¿Y a quiénes
::¿Y a cuanto::¿Y a cuánto
::¿Y a cuanta::¿Y a cuánta
::¿Y a cuantos::¿Y a cuántos
::¿Y a cuantas::¿Y a cuántas
::¿a que::¿A qué
::¿a cual::¿A cuál
::¿a cuales::¿A cuáles
::¿a donde::¿A dónde
::¿a quien::¿A quién
::¿a quienes::¿A quiénes
::¿a cuanto::¿A cuánto
::¿a cuanta::¿A cuánta
::¿a cuantos::¿A cuántos
::¿a cuantas::¿A cuántas
::¡que::¡Qué
::¡cual::¡Cuál
::¡cuales::¡Cuáles
::¡donde::¡Dónde
::¡quien::¡Quién
::¡quienes::¡Quiénes
::¡cuando::¡Cúando
::¡cuanto::¡Cuánto
::¡cuantos::¡Cuántos
::¡cuanta::¡Cuánta
::¡cuantas::¡Cuántas
::¡De que::¡De qué
::¡De cual::¡De cuál
::¡De cuales::¡De cuáles
::¡De donde::¡De dónde
::¡De quien::¡De quién
::¡De quienes::¡De quiénes
::¡De cuando::¡De cúando
::¡De cuanto::¡De cuánto
::¡De cuantos::¡De cuántos
::¡De cuanta::¡De cuánta
::¡De cuántas::¡De cuántas
::¡Y que::¡Y qué
::¡Y cual::¡Y cuál
::¡Y cuales::¡Y cuáles
::¡Y donde::¡Y dónde
::¡Y quien::¡Y quién
::¡Y quienes::¡Y quiénes
::¡Y cuando::¡Y cúando
::¡Y cuanto::¡Y cuánto
::¡Y cuantos::¡Y cuántos
::¡Y cuanta::¡Y cuánta
::¡Y cuántas::¡Y cuántas
::¡Y de que::¡Y de qué
::¡Y de cual::¡Y de cuál
::¡Y de cuales::¡Y de cuáles
::¡Y de donde::¡Y de dónde
::¡Y de quien::¡Y de quién
::¡Y de quienes::¡Y de quiénes
::¡Y de cuando::¡Y de cúando
::¡Y de cuanto::¡Y de cuánto
::¡Y de cuantos::¡Y de cuántos
::¡Y de cuanta::¡Y de cuánta
::¡Y de cuántas::¡Y de cuántas
::¡Y a que::¡Y a qué
::¡Y a cual::¡Y a cuál
::¡Y a cuales::¡Y a cuáles
::¡Y a donde::¡Y a dónde
::¡Y a quien::¡Y a quién
::¡Y a quienes::¡Y a quiénes
::¡Y a cuanto::¡Y a cuánto
::¡Y a cuantos::¡Y a cuántos
::¡Y a cuanta::¡Y a cuánta
::¡Y a cuántas::¡Y a cuántas
::¡a que::¡A qué
::¡a cual::¡A cuál
::¡a cuales::¡A cuáles
::¡a donde::¡A dónde
::¡a quien::¡A quién
::¡a quienes::¡A quiénes
::¡a cuanto::¡A cuánto
::¡a cuanta::¡A cuánta
::¡a cuantos::¡A cuántos
::¡a cuantas::¡A cuántas
::¡como::¡Cómo
::¡por que::¡Por qué
;============================
::rr hh::RR. HH.
::rrhh::RR. HH.
::rr.hh.::RR. HH.
;============================
::comistes::comiste
::vinistes::viniste
::pensastes::pensaste
::hablastes::hablaste
::dejastes::dejaste
;============================
::todavía::todavía
::mensajesito::mensajecito
::ratonsito::ratoncito
::nubesita::nubecita
::trajesito::trajecito
::cochesito::cochecito
::mujersita::mujercita
::hombresillo::hombrecillo
::geniesillo::geniecillo
::piesito::piecito
::pecesito::pececito
::lunatico::lunático
::lunaticos::lunáticos
::lunatica::lunática
::lunaticas::lunáticas
::antidoto::antídoto
::antidotos::antídotos
::monosilaba::monosílaba
::monosilabas::monosílabas
::obstaculo::obstáculo
::obstaculos::obstáculos
::cadaver::cadáver
::cadaveres::cadáveres
::fragil::frágil
::fragiles::frágiles
::polvoras::pólvoras
::frivolo::frívolo
::frivolos::frívolos
::hectarea::hectárea
::hectareas::hectáreas
::evaporacion::evaporación
::helice::hélice
::helices::hélices
::huracan::huracán
::violin::violín
::cojin::cojín
::sabana::sábana
::autobus::autobús
::avion::avión
::embarcacion::embarcación
::educacion::educación
::epoca::época
::cuestion::cuestión
::encontrare::encontraré
::relampago::relámpago
::formacion::formación
::cirugia::cirguía
::sente::senté
::capitalizacion::capitalazación
::multiple::múltiple
::multiples::múltiples
::estacion::estación
::convencion::convención
::gestacion::gestación
::germinacion::germinación
::apreciacion::apreciación
::despreciacion::despreciación
::amortizacion::amortización
::reducira::reducirá
::sistematico::sistemático
::sistematica::sistemática
::sistematicos::sistemáticos
::sistematicas::sistemáticas
::valuacion::valuación
::renumeracion::renumeración
::emision::emisión
::explicitamente::explícitamente
::cupon::cupón
::circulacion::circulación
::corporacion::corporación
::despreciaria::despreciaría
::apreciaria::apreciaría
::estrategico::estratégico
::estrategica::estratégica
::estrategicas::estratégicas
::estrategicos::estratégicos 
::tactico::táctico
::tactica::táctica
::tacticas::tácticas
::tacticos::tácticos
::inversion::inversión
::compañias::compañias
::juridico::jurídico
::juridicos::jurídicos
::dinamico::dinámico
::dinamicos::dinámicos
::dinamica::dinámica
::dinamicas::dinámicas
::exitos::éxitos
::exito::éxito
::comparacion::comparación
::economica::económica
::economicas::económicas
::economia::economía
::economias::economías 
::metodologia::metodología
::metodologias::metodologías
::liquidacion::liquidación
::padecia::padecía
::padecias::padecías
::padecian::padecían
::existian::existían
::comercializacion::comercialización 
::regulacion::regulación
::desregulacion::desregulación
::capacitacion::capacitación
::epica::épica
::epicas::épicas
::epico::épico
::epicos::épicos 
::epocas::épocas 
::transmision::trasmisión
::metodologico::metodólogico
::metodologicos::metodólogicos
::metodologica::metodólogica
::metodologicas::metodólogicas
::encarnacion::encarnación
::edificacion::edificación
::nacion::nación
::oir::oír
::buzon::buzón
::brujula::brújula
::telefono::teléfono
::telefonos::teléfonos
::formacion::formación
::posicion::posición
::inclinacion::inclinación
::camara::cámara
::tabano::tábano
::teologia::teología
::biologia::biología
::tetrico::tétrico
::hermofiloco::hermofílico
::estabamos::estábamos
::teniamos::teníamos
::eramos::éramos
::podiamos::podíamos
::realizacion::realización
::inhibicion::inhibición
::capacitacion::capacitación
::teneria::tenería
::panaderia::panadería
::vinateria::vinatería
::zapateria::zapatería
::raton::ratón
::maton::matón
::tason::tasón
::mandandome::mandándome
::enviandome::enviándome
::costelacion::costelación
::computacion::computación
::epilogo::epílogo
::elaboracion::elaboración
::diacono::diácono
::anecdota::anéctoda
::anecdotas::anéctodas
::mensajeria::mensajería
::sensacion::sensación
::diacritico::diacrítico
::tempano::témpano
::principe::príncipe
::principes::príncipes
::cesped::césped
::subterraneo::subterráneo
::betun::betún
::acuatico::acuático
::acuaticos::acuáticos
::acuatica::acuática
::acuaticas::acuáticas
::vehiculo::vehículo
::vehiculos::vehículos
::atmosfera::atmósfera
::lapiz::lápiz
::atmosferas::atmósferas
::baston::bastón
::corazonsito::corazoncito
::lucesita::lucecita
::redesilla::redecilla
::fonetico::fonético
::foneticos::fonéticos
::fonetica::fonética
::foneticas::fonéticas
::ortografico::ortográfico
::ortograficos::ortográficos
::ortografica::ortográfica
::ortograficas::ortográficas
::esdrujula::esdrújula
::esdrujulas::esdrújulas
::tasita::tacita
::proxima::próxima
::proximas::próximas
::proximo::próximo
::proximos::próximos
::electrica::eléctrica
::electricas::eléctricas
::electrico::eléctrico
::electricos::eléctricos
::redaccion::redacción::
::volvio::volvió
::volvia::volvía
::situacion::situación
::angel::ángel
::idolo::ídolo
::chabon::chabón
::cancer::cáncer
::erotico::erótico
::eroticos::eróticos
::solido::sólido
::solidos::sólidos
::solida::sólida
::solidas::sólidas
::pedofilo::pedófilo
::pedofilos::pedófilos
::pedofila::pedófila
::pedofilas::pedófilas
::humillacion::humillación
::preguntandole::preguntándole
::respondiendole::respondiéndole
::contestandole::contestándole
::comprometiendose::comprometiéndose
::ayudandose::ayudándose
::comiendose::comiéndose
::pajeandose::pajeándose
::distribuyendose::distribuyéndose
::pidio::pidió
::ideologia::idelogía
::relajese::relájese
::comprobo::comprobó
::biblico::bíblico
::biblicos::bíblicos
::biblica::bíblica
::biblicas::bíblicas
::galan::galán
::explicitamente::explícitamente
::dicipulo::dicípulo
::debil::débil
::debiles::débiles
::bendicion::bendición
::mastil::mástil
::habil::hábil
::aerodromo::aeródromo
::cabala::cábala
::ductil::dúctil
::atras::atrás
::condor::cóndor
::oceano::océano
::sindrome::síndrome
::diacritica::diacrítica
::comera::comerá
::escorpion::escorpión
::decada::década
::oxigeno::oxígeno
::sovietico::soviético
::triangulo::triángulo
::sabra::sabrá
::queria::quería
::conocia::conocía
::mismisimo::mismísimo
::polemica::polémica
::polemicas::polémicas
::cagon::cagón
::tonteria::tontería
::tonterias::tonterías
::caimos::caímos
::austero::aústero
::austeros::aústeros
::soñe::soñé
::escribire::escribiré
::escribira::escribirá
::escribiras::escribirás
::caratula::carátula
::ateismo::ateísmo
::mimesis::mímesis
::sarcasticamente::sarcásticamente
::retorico::retórico
::retoricos::retóricos
::retorica::retórica
::retoricas::retóricas
::haciendose::haciéndose
::mandibula::mandíbula
::mandibulas::mandíbulas
::ejercito::ejército
::ejercitos::ejércitos
::hipnotico::hipnótico
::hipnoticos::hipnóticos
::hipnotica::hipnótica
::hipnoticas::hipnóticas
::platonico::platónico
::platonicos::platónicos
::platonica::platónica
::platonicas::platónicas
::escobillon::escobillón
::extraida::extraída
::adaptacion::adaptación
::tiponimo::tipónimo
::instruccion::instrucción
::alegoria::alegoría
::metafora::metáfora
::metaforas::metáforas
::negacion::negación
::hiperbole::hipérbole
::hiperboles::hipérboles
::ironia::ironía
::ironias::ironías
::preoracion::preoración
::epilogos::epílogos
::manten::mantén
::tiponimos::tipónimos
::recien::recién
::frances::francés
::teton::tetón
::angulo::ángulo
::angulos::ángulos
::enfasis::énfasis
::boligrafos::bolígrafos
::decadas::décadas
::asociacion::asociación
::se empleo::se empleó
::se presento::se presentó
::haciendole::haciéndole
::humedo::húmedo
::humedos::húmedos
::humeda::húmeda
::humedas::húmedas
::adios::adiós
::aparecian::aparecían
::aprendi::aprendi
::astronomia::astronomía
::bosqueje::bosquejé
::comprendi::comprendí
::conocere::conoceré
::creia::creía
::deshollino::deshollinó
::dirigio::dirigió
::dirigi::dirigí
::divise::divisé
::elegia::elegía
::elejia::elegía
::elejía::elegía
::examinenlo::examínenlo
::abrio::abrió
::aconsejo::aconsejó
::vinculo::vínculo
::vinculos::vínculos
::tratandose::tratándose
::timidamente::tímidamente
::tratare::trataré
::tosio::tosío
::toseria::tosería
::sorprendio::sorprendió
::sintio::sintió
::simularia::simularía
::sere::seré
::seran::serán
::abrire::abriré
::pajaros::pájaros
::holistico::holístico
::holisticos::holísticos
::holistica::holística
::holisticas::holísticas
::oyo::oyó
::oia::oía
::oias::oías
::oian::oían
::oceanos::océanos
::oidos::oídos
::perdera::perderá
::metalico::metálico
::metalicos::metálicos
::metalica::metálica
::lapices::lápices
::lampara::lámpara
::lamparas::lámparas
::impresion::impresión
::indultaras::indultarás
::geografia::geografía
::esten::estén
::excepcion::excepción
::diciendome::diciéndome
::diciendole::diciéndole
::diciendoles::diciéndoles
::digestion::digestión
::dibuje::dibujé
::diran::dirán
::diria::diría
::dirian::dirían
::dirias::dirías
::daria::daría
::aprendi::aprendí
::creyo::creyó
::concedio::concedió
::concedia::concedía
::concedias::concedías
::concedian::concedían
::comprendera::comprenderá
::jupiter::júpiter
::daran::darán
::daria::daría
::darias::darías
::darian::darían
::cumplia::cumplía
::cumplias::cumplías
::cumplian::cumplían
::cumplio::cumplió
::comprendio::compredió
::añadi::añadí
::estes::estés
::estare::estaré
::escurrio::escurrió
::esforce::esforcé
::encubrio::encubrío
::encubrio::encubría
::geografias::geografías
::geografo::geógrafo
::geografos::geógrafos
::geografa::geógrafa
::geografas::geógrafas
::habre::habré
::conducia::conducía
::conducian::conducían
::conducias::conducías
::tension::tensión
::cumulo::cúmulo
::merito::mérito
::meritos::méritos
::sentire::sentiré
::comere::comeré
::sexologo::sexólogo
::operacion::operación
::frustacion::frustación
::circuncision::circuncisión
::conformandose::conformándose
::llamandose::llamándose
::comprendiendose::comprendiéndose
::estrogeno::estrógeno
::estrogenos::estrógenos
::deteriorandose::deteriorándose
::faloplastia::faloplastía
::faloplastias::faloplastías
::inyecto::inyectó
::frio::frío
::frios::fríos
::cubriria::cubriría
::estaras::estarás
::varia::varía
::caia::caía
::estaria::estaría
::traumatica::traumática
::terapeutica::terapeútica
::esplendido::espléndido
::metalicas::metálicas
::preambuulo::preámbulo
::preambuulos::preámbulos
::provision::provisión
::petalo::pétalo
::petalos::pétalos
::regalare::regalaré
::rie::ríe
::rien::ríen
::servirian::servirían
::serviria::serviría
::servirias::servirías
::adivinaran::adivinarán
::habria::habría
;~ ::hacia::hacía
::hacian::hacían
::hacias::hacías
::imageginense::imagínense
::informese::infórmese
::encendia::encendía
::encendias::encendías
::encendian::encendían
::haciendolo::haciéndolo
::haciendolos::haciéndolos
::compartis::compartís
::haciendola::haciéndola
::haciendolas::haciéndolas
::mostrandole::mostrándole
::mostrandola::mostrándola
::mostrandola::mostrándolo
::mostrandoles::mostrándoles
::mostrandolas::mostrándolas
::mostrandolas::mostrándolos
::simpatia::simpatía
::decision::decisión
::darsela::dársela
::darselas::dárselas
::generacion::generación
::consideracion::consideración
::implementacion::implementación
::formulacion::formulación
::evaluacion::evaluación
::sociologias::sociologías
::vinculacion::vinculación
::bibliografias::bibliografías
::seleccion::selección
::coordinacion::coordinación
::revision::revisión
::podras::podrás
::ejecucion::ejecución
::deberas::deberás
::deberan::deberán
::confirmaria::confirmaría
::confirmarias::confirmarías
::confirmarian::confirmarían
::renunciaria::renunciaría
::renunciarias::renunciarías
::terminos::términos
::renunciarian::renunciarían
::presentacion ::presentación
::conformacion::conformación
::instrumentacion::instrumentación
::calificacion::calificación
::tomaria::tomaría
::tomarias::tomarías
::alineacion::alineación
::tomarian::tomarían
::correccion::corrección
::microeconomia::microeconomía
::macroeconomia::macroeconomía
::microeconomico::microeconómico
::microeconomica::microeconómica
::microeconomicas::microeconómicas
::microeconomicos::microeconómicos
::macroeconomico::macroeconómico
::macroeconomica::macroeconómica
::macroeconomicas::macroeconómicas
::macroeconomicos::macroeconómicos
::demografica::demográfica
::demograficas::demográficas
::demografico::demográfico
::demograficos::demográficos
::generico::genérico
::genericos::genéricos
::generica::genérica
::genericas::genéricas
::integracion::integración
::margenes::márgenes
::obtencion::obtención
::produccion::producción
::adicion::adición
::aumentaria::aumentaría
::aumentarias::aumentarías
::aumentarian::aumentarían
::estarias::estarías
::estarian::estarían
::concentrica::concéntrica
::concentricas::concéntricas
::diversificacion::diversificación
::variacion::variación
::basica::basicá
::basicas::basicás
::basicos::basicós
::reduccion::reducción
::intuicion::intuición
::participacion::participacivn
::dimension::dimensión
::distribucion::distribución
::tio::tío
::tios::tíos
::tia::tía
::tias::tías
::utiles::útiles
::actuan::actúan
::buscarsela::buscársela
::bancarsela::bancársela
::dandose::dándose
::realizandose::realizándose
::meditacion::meditación
::creiste::creíste
::inutil::inútil
::inutiles::inútiles
::psicologico::psicológico
::psicologicos::psicológicos
::psicologica::psicológica
::psicologicas::psicológicas
::creersela::creérsela
::creerselo::creérselo
::gigolo::gígolo
::gigolos::gígolos
::ojala::ojalá
::pendulo::péndulo
::pendulos::péndulos
::ridiculo::ridículo
::ridiculos::ridículos
::ridicula::ridícula
::ridiculas::ridículas
::picardia::picardía
::picardias::picardías
::virgenes::vírgenes
::vacio::vacío
::vacios::vacíos
::vacia::vacía
::vacias::vacías
::monton::montón
::tontin::tontín
::xilofon::xilofón
::sifon::sifón
::subtitulo::subtítulo
::subtitulos::subtítulos
::convertis::convertís
::heroe::héroe
::heroes::héroes
::projimo::prójimo
::projimos::prójimos
::projima::prójima
::projimas::prójimas
::odiandolo::odiándolo
::odiandolos::odiándolos
::compañia::compañía
::compania::compañía
::companía::compañía
::dietetica::dietética
::dieteticas::dietéticas
::dietetico::dietético
::dieteticos::dietéticos
::sintetico::sintético
::sinteticos::sintéticos
::sitentica::sintética
::sinteticas::sintéticas
::camison::camisón
::cancelaria::cancelaría
::cancelarias::cancelarías
::aceptaria::aceptaría
::aceptarias::aceptarías
::existira::existirá
::existiran::existirán
::icono::ícono
::iconos::íconos
::traere::traeré
::pronunciacion::pronunciación
::espiritu::espíritu
::espiritus::espíritus
::decis::decís
::encontras::encontrás
::semaforo::semáforo
::semaforos::semáforos
::autentico::auténtico
::autenticos::auténticos
::autentica::auténtica
::autenticas::auténticas
::tene::tené
::alimentandome::alimentándome
::comiendome::comiéndome
::comiendole::comiéndole
::alimentandolo::alimentándolo
::alimentandolos::alimentándolos
::preparandonos::preparándonos
::preparandome::preparándome
::preparandole::preparándole
::preparandoles::preparándoles
::acuerdese::acuérdese
::acuerdense::acuérdense
::impediran::impedirán
::interrupiran::interrupirán
::amedentro::amedrentó
::denunciamos::denuncíamos
::armonia::armonía
::armonias::armonías
::caratula::carátula
::caratulas::carátulas
::erroneo::erróneo
::erroneos::erróneos
::erronea::errónea
::erroneas::erróneas
::creacion::creación
::mediodia::mediodía
;============================
::cacita::casita
::camicita::camisita
::becito::besito
::mecita::mesita
::pecito::pesito
::bolcito::bolsito
::cocita::cosita
::rocita::rosita
;============================
::benitez::Benítez
::bolivar::Bolívar
::cristobal::Cristóbal
::dominguez::Domínguez
::estevez::Estévez
::gomez::Gómez
::martinez::Martínez
::martínez::Martínez
::mendez::Méndez
::méndez::Méndez
::tunez::Túnez
::túnez::Túnez
::velazquez::Velázquez
::velázquez::Velázquez
::ramirez::Ramírez
::ramírez::Ramírez
::suarez::Suárez
::vélez::Vélez
::julian::Julián
::julio::Julio
::omar::Omar
::sanchez::Sánchez
::sánchez::Sánchez
::silvio::Silvio
::rodriguez::Rodrigez
::pamela::Pamela
::richard::Richard
::jose::José
::maria::María
::enzo::Enzo
::pablo::Pablo
::bergoglio::Bergoglio
::gonzalo::Gonzalo
::ramona::Ramona
::danel::Danel
::javier::Javier
::martin::Martín
::rodrigo::Rodrigo
::antonio::Antonio
::antonia::Antonia
::hernan::Hernán
::hernán::Hernán
::daniel::Daniel
::mariano::Mariano
::mariana::Mariana
::florencia::Florencia
::ezequiel::Ezequiel
::camila::Camila
::aguero::Agüero
::kun::Kun
::sofia::Sofía
::peres::Peres
::ricardo::Ricardo
::lilian::Lilian
::liliana::Liliana
::alejandro::Alejandro
::alejandría::Alejandría
::alejandria::Alejandría
::alejandra::Alejandra
::veronica::Verónica
::verónica::Verónica
::yesica::Yésica
::yésica::Yésica
::luisana::Luisana
::sabrina::Sabrina
::zaira::Zaira
::luli::Luli
::eleonora::Eleonora
::emilio::Emilio
::gimena::Gimena
::ingrid::Ingrid
::paola::Paola
::karina::karina
::flavia::Flavia
::flavio::Flavio
::evangelina::Evangelina
::jimena::Jimena
::nicole::Nicole
::monica::Mónica
::mónica::Mónica
::jenny::Jenny
::carla::Carla
::mercedes::Mercedes
::cecilia::Cecilia
::agustina::Agustina
::noelia::Noelia
::jesica::Jésica
::jésica::Jésica
::julie::Julie
::vanesa::Vanesa
::pia::Pía
::pía::Pía
::fatima::Fátima
::fátima::Fátima
::guillermina::Guillermina
::erica::Erica
::ximena::Ximena
::carola::Carola
::viviana::Viviana
::magui::Magui
::maggie::Maggie
::solange::Solange
::evangelina::Evangelina
::liz::Liz
::alexandra::Añexamdra
::erika::Erica
::lourdes::Lourdes
::calu::Calu
::wanda::Wanda
::noelia::Noelia
::antonela::Antonela
::cristina::Cristina
::mauricio::Mauricio
::macri::Macri
::kirchner::Kirchner
::harry::Harry
::arnaldo::Arnaldo
::iris::Iris
::lionel::Lionel
::barack::Barack
::alfonsin::Alfonsín
::alfonsín::Alfonsín
::nelson::nelson
::ernesto::Ernesto
::charly::Charly
::alberto::Alberto
::adrian::Adrían
::adrían::Adrían
::vilas::Vilas
::hermes::Hermes
::aaron::Aaron
::ortega::ortega
::suar::Suar
::alfredo::Alfredo
::alfreda::Alfreda
::cristobal::Cristóbal
::cristóbal::Cristóbal
::florencio::Florencio
::adolfo::Adolfo
::justin::Justin
::gandhi::Gandhi
::marley::Marley
::karl::Karl
::solanas::Solanas
::adolf::Adolf
::adolfo::Adolfo
::adolfino::Adolfino
::adolfina::Adolfina
::fangio::Fangio
::eduardo::Eduardo
::faustino::Faustino
::rene::Rene
::florencio::Florencio
::mirta::Mirta
::mirtha::Mirtha
::fontanarrosa::Fontanarrosa
::ramon::Ramón
::ramón::Ramón
::gilda::Gilda
::bartolome::Bartolomé
::bartolomé::Bartolomé
::prat gay::Prat Gay
::eugenia::Eugenia
::vidal::Vidal
::candelaria::Candelaria
::tinelli::Tinelli
::villani::Villani
::carlos::Carlos
::george::George
::orwell::Orwell
::hitler::Hitler
::charly::Charly
::jorge::Jorge
::lopez::López
::lópez::López
::Susana::Susana
::fito::Fito
::paez::Páez
::páez::Páez
::thomas::Thomas
::hector::Héctor
::emma::Emma
::watson::Watson
::griesa::Griesa
::micheti::Michetti
::michetti::Michetti
::gabriela::Gabriela
::gabriel::Gabriel
::fenandez::Fernández
::fenández::Fernández
::moyano::Moyano
::banco central::Banco Central
::amado boudou::Amado Boudou
::boudou::Boudou
::milagro sala::Milagro Sala
::milagro salas::Milagro Sala
::milagros sala::Milagro Sala
::milagros salas::Milagro Sala
::victor::Víctor
::víctor::Víctor
::hugo morales::Hugo Morales
::hugo::Hugo
::guillermo::Guillermo
::nielsen::Nielsen
::einstein::Einstein
::gonzalez::González
::gonzález::González
::nestor::Néstor
::jimenez::Jiménez
::ortigoza::Ortigoza
::kim::Kim
::cromañon::Cromañon
::osvaldo::Osvaldo
::gordon::Gordon
::darin::Darín
::darín::Darín
::freeman::Freeman
::peron::Perón
::perón::Perón
::belgrano::Belgrano
::rivadavia::Rivadavia
::chavez::Chávez
::miguel::Miguel
::luis::Luis
::juan::Juan
::ignacio::Ignacio
::nicolas::Nicolás
::nicolás::Nicolás
::alberto::alberto
::maria::María
::maría::María
::belen::Belén
::belén::Belén
::fernando::Fernando
::fernanda::Fernanda
::laura::Laura
::manuel::Manuel
::carlos::Carlos
::pablo::Pablo
::valentino::Valentino
::valentino::Valentina
::martina::Martina
::santiago::Santiago
::lucia::lucía
::lucía::Lucía
::catalina::Catalina
::elena::Elena
::emilia::Emilia
::derek::Derek
::francisco::Francisco
::alonso::Alonso
::bautista::Bautista
::rafael::Rafael
::andres::Andrés
::andrés::Andrés
::oliver::Oliver
::pedro::Pedro
::julian::Julían
::julían::Julían
::alexander::Alexander
::sergio::Sergio
::lorenzo::Lorenzo
::antonio::Antonio
::antonia::Antonia
::rosina::Rosian
::anabella::Anabella
::ayelen::Ayelén
::ayelén::Ayelén
::beatriz::Beatriz
::isabel::Isabel
::sara::Sara
::silvia::Silvia
::mafalda::Mafalda
::daniela::Daniela
::diana::Diana
::dahiana::Dahiana
::claudia::Claudia
::camila::Camila
::axel::Axel
::angela::Angela
::jonathan::Jonathan
::jonatan::Jonatán
::jonatán::Jonatán
::esteban::Esteban
::luciano::Luciano
::eric::Eric
::jonathan::Jonathan
::luciana::Luciana
::ivan::Iván
::iván::Iván
::alan::Alan
::ciro::Ciro
::paula::Paula
::benjamin::Benjamín
::damian::damían
::damian::Damían
::thiago::Thiago
::diego::Diego
::samuel::Samuel
::sebastian::Sebastían
::sebastían::Sebastían
::bruno::Bruno
::lucas::Lucas
::joaquin::Joaquín
::joaquín::Joaquín
::david::David
::gilmour::Gilmour
::agustin::Agustín
::agustín::Agustín
::susano::Susano
::ofelia::Ofelia
::yaro::Yaro
::vanina::Vanina
::estefania::Estefanía
::natalie::Natalie
::marina::Marina
::janah::Janah
::celina::Celina
::nazarena::Nazarena
::nazareno::Nazareno
::natali::Natalia
::ariana::Ariana
::natacha::Natacha
::magali::Magali
::griselda::Griselda
::garcia::García
::denise::Denise
::denise::Denis
::victorio::Victorio
::michel::Michel
::leandro::Leandro
::raul::Raúl
::raúl::Raúl
::ivo::Ivo
::batistuta::Batistuta
::aimar::Aimar
::irene::Irene
::estefano::Estefano
::estefani::Estafani
::eugenio::eugenio
::eugene::Eugene
::carolina::Carolina
::alberto::Alberto
::felipe::Felipe
::ian::Ian
::hugo::Hugo
::rodrigo::Rodrigo
::simon::Simón
::isaac::Isaac
::emanuel::Emanuel
::vicente::Vicente
::liam::Liam
::susano::Susano
::ofelia::Ofelia
::irene::Irene
::estefano::Estefano
::estefani::Estafani
::eugenio::eugenio
::eugene::Eugene
::carolina::Carolina
::alberto::Alberto
::cecilio::Cecilio
::heidi::Heidi
::judith::Judith
::vierci::Vierci
::nilda::Nilda
::patricio::Patricio
::patricia::patricia
::roberto::Roberto
::julieta::Julieta
::gian::Gian
::gianni::Gianni
::enrique::Enrique
::angie::angie
::araceli::Araceli
::alex::Alex
::ariel::Ariel
::ariela::Ariela
::yamila::Yamila
::valentina::Valentina
::valeria::Valeria
::natalia::Natalia
::brianna::Brianna
::guadalupe::Guadalupe
::francesca::Francesca
::delfina::Delfina
::rafaela::Rafela
::maia::Maia
::constanza::Constanza
::eva::Eva
::laurita::Laurita
::danna::Danna
::aitana::Aitana
::brenda::Brenda
::elizabeth::Elizabeth
::antonella::Antonella
::josefina::Josefina
::amalia::Amalia
::maia::maia
::micaela::Micaela
::elisa::elisa
::nahuel::Nahuel
::rodolfo::Rodolfo
::walter::Walter
::salem::Salem
::yamil::Yamil
::andrea::Andrea
::marcelo::Marcelo
::marcela::Marcela
::moises::Moisés
::moisés::Moisés
::facunda::Facunda
::virginia::Virginia
::octavio::Octavio
::octavia::Octavia
::iriarte::Iriarte
::josefino::Josefino
::agostina::Agostina
::ivana::Ivana
::fabio::Fabio
::fabian::Fabían
::fabían::Fabían
::michael::Michael
::melina::Melina
::samantha::Samantha
::naira::Naria
::ivanna::Ivanna
::cinthia::Cinthia
::facundo::Facundo
::federico::Federico
::germán::Germán
::german::Germán
::giancarlo::Giancalo
::dana::Dana
::kevin::Kevin
::xoan::Xoan
::gaston::Gastón
::gastón::Gastón
::guido::guido
::renzo::Renzo
::ramiro::Ramiro
::gustavo::Gustavo
::lucrecia::Lucrecia
::ines::Inés
::inés::Inés
::matias::Matías
::matías::Matías
::ethel::Ethel
::giampaolo::Giampaolo
::adrian::Adrían
::adrían::Adrían
::daiana::Daiana
::ruben::Ruben
::ferreyra::Ferreyra
::rossi::Rossi
::maximiliano::Maximiliano
::leopoldo::Leopoldo
::leonardo::Leonardo
::bianca::Bianca
::camilo::Camilo
::iair::Irai
::jhon::Jhon
::cinthia::Cinthia
::miriam::Miriam
::alexis::Alexis
;============================
::steven::Steven
::spielberg::Spielberg
;============================
::england::England
::spain::Spain
::united states::United States
;============================
::Cancún::Cancún
::Cancun::Cancún
::Bariloche::Bariloche
::Catamarca::Catamarca
::Chubut::Chubut
::Formosa::Formosa
::Jujuy::Jujuy
::La Pampa::La Pampa
::La Rioja::La Rioja
::Mendonza::Mendonza
::Nuequen::Nuequén
::Nuequén::Nuequén
::Santa Cruz::Santa Cruz
::Santa Fe::Santa Fe
::Tierra del Fuego::Tierra del Fuego
::Tucuman::Tucuman
::rios::ríos
::Afganistan::Afganistán
::Albania::Albania
::Angola::Angola
::Armenia::Armenia
::Aruba::Aruba
::Australia::Australia
::Austria::Austria
::Bulgaria::Bulgaria
::Camboya::Camboya
::Chipre::Chipre
::Costa Rica::Costa Rica
::Costa de Marfil::Costa de Marfil
::Cuba::Cuba
::Dinamarca::Dinamarca
::Croacia::Croacia
::Colombia::Colombia
::Camerun::Camerún
::Camerún::Camerún
::Croacia::Croacia
::Dominica::Dominica
::Corea::Corea
::Egipto::Egipto
::Etiopia::Etiopia
::Filipinas::Filipinas
::Fiyi::Fiyi
::Gabon::Gabon
::Gambia::Gambia
::Eslovenia::Eslovenia
::Eslovaquia::Eslovaquia
::El Vaticano::El Vaticano
::Georgia::Georgia
::Ghana::Ghana
::Indonesia::Indonesia
::Iraq::Iraq
::Iran::Irán
::Irán::Irán
::Honduras::Honduras
::Hong Kong::Hong Kong
::Hungría::Hungría
::Hungria::Hungría
::Haiti::Haiti
::Guyana::Guyana
::Guinea::Guinea
::Islas Malvinas::Islas Malvinas
::Marshall::Marshall
::Jamaica::Jamaica
::Israel::Israel
::Libio::Libio
::Liberia::Liberia
::Letonia::Letonia
::Lesoto::Lesoto
::Lituania::Lituania
::Luxemburgo::Luxemburgo
::Macedonia::Macedonia
::Madagascar::Madagascar
::Malasia::Malasia
::Malta::Malta
::Marruecos::Marruecos
::Mongolia::Mongolia
::Monaco::Monaco
::Nepal::Nepal
::Nicaragua::Nicaragua
::Montenegro::Montenegro
::Nueva Zelanda::Nueva Zelanda
::Peru::Peru
::Polonia::Polonia
::Portugal::Portugal
::Rumania::Rumania
::Singapur::Singapur
::Serbia::Serbia
::Siria::Siria
::Sudafrica::Sudafrica
::Suecia::Suecia
::Suiza::Suiza
::Somalia::Somalia
::Senegal::Senegal
::Tailandia::Tailandia
::Tanzania::Tanzania
::Taiwan::Taiwan
::Tonga::Tonga
::Turquia::Turquia
::Vietnam::Vietnam
::Venezuela::Venezuela
::Zambia::Zambia
::Tayikistan::Tayikistan
::Kenia::Kenia
::Etiopia::Etiopia
::Zimbabue::Zimbabue
::Yemen::Yemen
::india::India
::latinoamérica::Latinoamérica
::latinoamerica::Latinoamérica
::america::América
::américa::América
::argentina::Argentina
::japon::Japón
::japón::Japón
::finlandia::Finlandía
::finlandía::Finlandía
::brasil::Brasil
::rusia::Rusia
::francia::Francia
::alemania::Alemania
::chile::Chile
::portugal::Portugal
::paraguay::Paraguay
::bolivia::Bolivia
::uruguay::Uruguay
::mexico::México
::megico::México
::mejico::Méjico
::áfrica::África
::africa::África
::berlin::Berlín
::berlín::Berlín
::moscu::Moscú
::inglaterra::Inglaterra
::estados unidos::Estados Unidos
::real madrid::Real Madrid
::madrid::Madrid
::Belgica::Bélgica
::españa::España
::buenos aires::Buenos Aires
::bariloche::Bariloche
::hungria::Hungría
::cordoba::Córdoba
::santa fe::Santa Fe
::rio negro::Río Negro
::río negro::Río Negro
::canada::Canada
::mar chiquita::Mar Chiquita
::nueva zelanda::Nueva Zelanda
::italia::Italia
::antartida::Antártida
::antártida::Antártida
::copenhague::Copenhague
::morón::Morón
::moron::Morón
;============================
::san valentin::San Valentín
::infobae::Infobae
::unicef::Unicef
::nike::Nike
::coca cola::Coca Cola
::telam::Télam
::télam::Télam
::universidad de palermo::Universidad de Palermo
::dni::DNI
::afip::AFIP
::reddit::Reddit
::taringa::Taringa
::poringa::Poringa
::wikipedia::Wikipedia
::clarin::Clarín
::autohotkey::AutoHotkey
::scite::SciTE
::scite4autohotkey::SciTE4AutoHotkey
::whatsapp::WhatsApp
::identi::Identi
::fundeu::Feundéu
::warez::Warez
::rae::RAE
::bbva::BBVA
::steam::Steam
::pepsi::Pepsi
::amazon::Amazon
::wikia::Wikia
::spotify::Spotify
::microsoft::Microsoft
::league of legends::League of Legends
::facebook::Facebook
::twitter::Twitter
::snapchat::Snapchat
::coto::Coto
::acrobat::Acrobat
::ascci::ASCCI
::fb::FB
::nsfw::NSFW
::seo::SEO
::rss::RSS
::api::API
::url::URL
::dmca::DMCA
::uocra::UOCRA
::la campora::La Cámpora
;============================
::demaciado::demasiado
::berruga::verruga
::preven::preveen
::prevén::preveen
::llendo::yendo
::elejir::elegir
::eligan::elijan
::eliga::elija
::automatisidad::automaticidad
;============================
::fé::fe
::fuí::fui
::dió::dio
::fué::fue
::vió::vio
;============================
::flicka::Flicka
::flickas::Flickas